### ISSUE TITLE
multiple templates

### ISSUE THREAD

**Issue by jmsobe** [mtwebit/DataSet#3]
Have a question regarding your module. Is there a method to import data from an XML file into multiple templates, certain data would be imported into one template other data would be used with a secondary template?  I suppose this can be handled with multiple import files, but wondering if this is possible with a single import file.

**Comment by mtwebit** [comment]
It is not possible to import content into multiple templates using a single rule.
You can create a new import rule and refer to an already uploaded document in that rule. This way you don't have to upload multiple copies of the same document.
